### ISSUE TITLE
Can't complete a full sync due to error

### ISSUE THREAD

**Issue by prossberg** [hk21702/YA-GCal-Notion-Sync-Script#16]
I get this error when trying to do a full sync. I think the script messes up when there are things written in the Location, Description or Calender field.

```
Error: {"object":"error","status":400,"code":"validation_error","message":"Calendar is not a property that exists. Description is not a property that exists. Location is not a property that exists. Date is not a property that exists."}
parseEvents	@ main.gs:252
syncFromGCal	@ main.gs:175
main	@ main.gs:32
```

**Comment by hk21702** [comment]
The error message seems more like the API isn't able to find your properties in your database? Doesn't seem to have anything to do with data existing in said properties already. Make sure the database is setup properly in terms of the names and datatypes. Also make sure that the database that you shared with your integration is the correct one.

**Comment by prossberg** [comment]
You are totally right. I updated to newer code and didn't see that those tags were added. That's why the events were working as before and it only threw the error when I did a full sync.
