### ISSUE TITLE
Deleting event in Notion doesn't delete in GCal

### ISSUE THREAD

**Issue by tatelax** [hk21702/YA-GCal-Notion-Sync-Script#29]
I've tried deleting the event in Notion as well as Tagging the event as Cancelled/Removed. The event doesn't delete in Notion.

However if I delete the event in GCal, it is deleted in Notion.

**Comment by tatelax** [comment]
Is this not possible due to Notion API limitations? Looks like it might be from what I can tell. But tagging should still work. For me it does nothing.

**Comment by hk21702** [comment]
Was able to reproduce and fix in #32.
