### ISSUE TITLE
Cannot read property 'end' of null

### ISSUE THREAD

**Issue by MrVallon412** [hk21702/YA-GCal-Notion-Sync-Script#4]
Hi ! 

Thanks to your reddit answer, I've fixed the date issues ! But now the script seem to have trouble with the "end" value. My basic knowledge of programing took a look, but couldn't find anything.

```
Error	
TypeError: Cannot read property 'end' of null
convertToGCalEvent	@ main.gs:497
syncToGCal	@ main.gs:53
main	@ main.gs:25
```

**Comment by hk21702** [comment]
Was able to replicate the issue and should be fixed in commit b8626aa6356614d9c59dee5ef4cf628f32ccfb4c. Was an issue with not handling pages without dates correctly when in the chance that a calendar was selected allowing it to get through the initial filter there.
