### ISSUE TITLE
ALL DAY event won't sync from GCal

### ISSUE THREAD

**Issue by barzoock** [hk21702/YA-GCal-Notion-Sync-Script#43]
Hello a "all day" event will sync from Notion to GCal.
But Won't Sync from GCal to Notion.

The issue seems to be with "ISO8601" convertation.

Please check the error I get:

> Error: {"object":"error","status":400,"code":"validation_error","message":"body failed validation: body.properties.Date.date.end should be a valid ISO 8601 date string, `null`, or `undefined`, instead was `\"12/23/2022\"`."}

I would appreciate it if you could help me fix the problem.
Thank you for your AMAZING script!

**Comment by hk21702** [comment]
I was able to replicate the issue. Seems to be the result of something changing in one of the APIs. Will get a fix out soon.
