### ISSUE TITLE
Hi! I've been using this script and it worked fine for the past month. But recently I've been getting this same error message:

### ISSUE THREAD

**Issue by hk21702** [hk21702/YA-GCal-Notion-Sync-Script#45]
Hi! I've been using this script and it worked fine for the past month. But recently I've been getting this same error message:

Error: API call to calendar.events.list failed with error: Sync token is no longer valid, a full sync is required.
syncFromGCal	@ main.js.gs:183
main	@ main.js.gs:38

I only have very rudimentary knowledge of coding, so I don't know how to perform this full sync. Hope you can assist!

_Originally posted by @hikarizun in https://github.com/hk21702/YA-GCal-Notion-Sync-Script/issues/3#issuecomment-1364506998_

**Comment by hk21702** [comment]
First, update your version of the script https://github.com/hk21702/YA-GCal-Notion-Sync-Script/wiki/Updating-the-Script%F0%9F%94%B8 then follow these instructions from the wiki: https://github.com/hk21702/YA-GCal-Notion-Sync-Script/wiki/FAQ-&-Common-Errors%F0%9F%94%BA#triggering-a-full-sync

**Comment by hikarizun** [comment]
I ran the fullSync and got this error:
TypeError: ignored_eIds.has is not a function
parseEvents	@ main.js.gs:212
syncFromGCal	@ main.js.gs:194
fullSync	@ main.js.gs:56

**Comment by hk21702** [comment]
Seems to be a bug. Try again with the latest version I just pushed.

**Comment by hikarizun** [comment]
It's working fine now. Thank you!
